### ISSUE TITLE
关于srearch

### ISSUE THREAD

**Issue by norwhereok** [Pcrab/hexo-theme-quark#2]
之前给您发过邮件，我在删除了hexo-generator-searchdb，安装hexo-generator-search之后搜索栏还是没有显示，在下载了插件之后我还需要配置文件吗？

**Comment by Pcrab** [comment]
要在站点的 config 文件（不是 theme 下的 config）中加入
``` yaml
search:
  path: search.xml
  field: post
```
其他配置可以看一下 [这里](https://github.com/wzpan/hexo-generator-search)
